### ISSUE TITLE
Make an API for this service

### ISSUE THREAD

**Issue by amitness** [bibhuticoder/nepali-summarizer#1]
Interesting project. Can you make an API as well for this? It'll be very useful.

**Comment by bibhuticoder** [comment]
its a client side JavaScript library. Since its lightweight it would be easier to use it at client side rather than server side.

**Comment by amitness** [comment]
That would work too. You could create a chrome extension for this. Here's how it would behave:
1. You goto a webpage, say "Kantipur"
2. Select a text
3. Right click and in context menu, there shall be "Summarize".
4. The summarized text is shown.

**Comment by bibhuticoder** [comment]
Thanks man. Its really a nice idea. I will work on it soon. :smile::smile:
